/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.unmsm.vista;

import com.sun.awt.AWTUtilities;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.border.SoftBevelBorder;
import pe.edu.unmsm.controlador.Coordinador;
import pe.edu.unmsm.modelo.datos.Curso;
import pe.edu.unmsm.modelo.datos.Malla;

/**
 *
 * @author Windows 10 Pro
 */
public final class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    CardLayout Lay;
    ArrayList<String> listaPreReq;
    ArrayList<Curso> plan;
    VistaInicio inicio;
    Coordinador co;
    TimerTask task;

    public Vista() {

        init();
        initComponents();

        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 20, 20);
        AWTUtilities.setWindowShape(this, forma);
        lbConfig.setForeground(Color.white);
        lbCurriculas.setForeground(new Color(204, 204, 204));
        lbResult.setForeground(new Color(204, 204, 204));

        Lay = (CardLayout) (pnOpciones.getLayout());
        Interface.establecerInfoVariables(jlbInfoNumHormigas,
                jlbInfoIterMax,
                jlbInfoMinCursosPermitidos,
                jlbInfoMaxCursosPermitidos,
                jlbInfoMinCreditosPermitidos,
                jlbInfoMaxCreditosPermitidos);
        Interface.inicializarListaDePlanes(cbxListaPlanes);
        listaPreReq = new ArrayList<>();
        plan = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        panelBase = new javax.swing.JPanel();
        pNav = new javax.swing.JPanel();
        pConfig = new javax.swing.JPanel();
        lbConfig = new javax.swing.JLabel();
        pCurriculas = new javax.swing.JPanel();
        lbCurriculas = new javax.swing.JLabel();
        pnlNavPlanGenerado = new javax.swing.JPanel();
        lbResult = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pnOpciones = new javax.swing.JPanel();
        pOConfig = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlbNumHormigas = new javax.swing.JLabel();
        inputNumHormigas = new javax.swing.JTextField();
        jlbMinCursosPermitidos = new javax.swing.JLabel();
        inputMinCur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputIterMax = new javax.swing.JTextField();
        jlbMaxCursosPermitidos = new javax.swing.JLabel();
        inputMaxCur = new javax.swing.JTextField();
        jlbMinCreditosPermitidos = new javax.swing.JLabel();
        inputMinCre = new javax.swing.JTextField();
        jlbMaxCreditosPermitidos = new javax.swing.JLabel();
        inputMaxCre = new javax.swing.JTextField();
        btnGuardarConfiguracion = new javax.swing.JButton();
        pnlInfo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlbInfoNumHormigas = new javax.swing.JLabel();
        jlbInfoIterMax = new javax.swing.JLabel();
        jlbInfoMinCursosPermitidos = new javax.swing.JLabel();
        jlbInfoMaxCursosPermitidos = new javax.swing.JLabel();
        jlbInfoMinCreditosPermitidos = new javax.swing.JLabel();
        jlbInfoMaxCreditosPermitidos = new javax.swing.JLabel();
        jlbInfovalores = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlbAlert = new javax.swing.JLabel();
        pOCurriculas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaPreRequisitos = new javax.swing.JTable();
        inputAPCodigo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        inputAPNombre = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        cbxCreditos = new javax.swing.JComboBox<>();
        inputAPPreReq = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnAgregarCurso = new javax.swing.JButton();
        btnAgregarPlan = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        inputAPNombrePlan = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnAgregarPreReq = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        tbListaCursos = new javax.swing.JTable();
        jlbAlertAPCursoAdd = new javax.swing.JLabel();
        jlbAlertAPPreReq = new javax.swing.JLabel();
        jlbAlertAPnombrePlan = new javax.swing.JLabel();
        pnlPlanGenerado2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Table3 = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Table4 = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Table5 = new javax.swing.JTable();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Table6 = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        Table7 = new javax.swing.JTable();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        Table8 = new javax.swing.JTable();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        Table9 = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        Table10 = new javax.swing.JTable();
        jlbNombrePlanG = new javax.swing.JLabel();
        pnlPlanGenrado1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnGenerarPlan = new javax.swing.JButton();
        cbxListaPlanes = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pNav.setBackground(new java.awt.Color(0, 0, 0));

        pConfig.setBackground(new java.awt.Color(0, 0, 0));
        pConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pConfigMouseReleased(evt);
            }
        });

        lbConfig.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lbConfig.setForeground(new java.awt.Color(204, 204, 204));
        lbConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbConfig.setText("Configuraciones");

        javax.swing.GroupLayout pConfigLayout = new javax.swing.GroupLayout(pConfig);
        pConfig.setLayout(pConfigLayout);
        pConfigLayout.setHorizontalGroup(
            pConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pConfigLayout.setVerticalGroup(
            pConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbConfig)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCurriculas.setBackground(new java.awt.Color(0, 0, 0));
        pCurriculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pCurriculasMouseReleased(evt);
            }
        });

        lbCurriculas.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lbCurriculas.setForeground(new java.awt.Color(204, 204, 204));
        lbCurriculas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCurriculas.setText("Agregar Plan");

        javax.swing.GroupLayout pCurriculasLayout = new javax.swing.GroupLayout(pCurriculas);
        pCurriculas.setLayout(pCurriculasLayout);
        pCurriculasLayout.setHorizontalGroup(
            pCurriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCurriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCurriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCurriculasLayout.setVerticalGroup(
            pCurriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCurriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCurriculas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNavPlanGenerado.setBackground(new java.awt.Color(0, 0, 0));
        pnlNavPlanGenerado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlNavPlanGeneradoMouseReleased(evt);
            }
        });

        lbResult.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lbResult.setForeground(new java.awt.Color(204, 204, 204));
        lbResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbResult.setText("Plan Generado");

        javax.swing.GroupLayout pnlNavPlanGeneradoLayout = new javax.swing.GroupLayout(pnlNavPlanGenerado);
        pnlNavPlanGenerado.setLayout(pnlNavPlanGeneradoLayout);
        pnlNavPlanGeneradoLayout.setHorizontalGroup(
            pnlNavPlanGeneradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavPlanGeneradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavPlanGeneradoLayout.setVerticalGroup(
            pnlNavPlanGeneradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavPlanGeneradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pNavLayout = new javax.swing.GroupLayout(pNav);
        pNav.setLayout(pNavLayout);
        pNavLayout.setHorizontalGroup(
            pNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNavLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(pConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCurriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNavPlanGenerado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        pNavLayout.setVerticalGroup(
            pNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pNavLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNavPlanGenerado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCurriculas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pConfig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnOpciones.setBackground(new java.awt.Color(231, 222, 222));
        pnOpciones.setPreferredSize(new java.awt.Dimension(963, 800));
        pnOpciones.setLayout(new java.awt.CardLayout());

        pOConfig.setBackground(new java.awt.Color(231, 228, 228));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlbNumHormigas.setText("Numeros de Hormigas");

        inputNumHormigas.setBackground(new java.awt.Color(246, 245, 245));
        inputNumHormigas.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputNumHormigas.setForeground(new java.awt.Color(102, 102, 102));
        inputNumHormigas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputNumHormigas.setCaretColor(new java.awt.Color(0, 0, 0));
        inputNumHormigas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputNumHormigas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputNumHormigas.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jlbMinCursosPermitidos.setText("Minimo de cursos de permitidos");

        inputMinCur.setBackground(new java.awt.Color(246, 245, 245));
        inputMinCur.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputMinCur.setForeground(new java.awt.Color(102, 102, 102));
        inputMinCur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputMinCur.setCaretColor(new java.awt.Color(0, 0, 0));
        inputMinCur.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputMinCur.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputMinCur.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabel3.setText("Iteraciones maximas");

        inputIterMax.setBackground(new java.awt.Color(246, 245, 245));
        inputIterMax.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputIterMax.setForeground(new java.awt.Color(102, 102, 102));
        inputIterMax.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputIterMax.setCaretColor(new java.awt.Color(0, 0, 0));
        inputIterMax.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputIterMax.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputIterMax.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jlbMaxCursosPermitidos.setText("Maximo de cursos permitidos");

        inputMaxCur.setBackground(new java.awt.Color(246, 245, 245));
        inputMaxCur.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputMaxCur.setForeground(new java.awt.Color(102, 102, 102));
        inputMaxCur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputMaxCur.setCaretColor(new java.awt.Color(0, 0, 0));
        inputMaxCur.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputMaxCur.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputMaxCur.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jlbMinCreditosPermitidos.setText("Minimo de creditos permitidos");

        inputMinCre.setBackground(new java.awt.Color(246, 245, 245));
        inputMinCre.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputMinCre.setForeground(new java.awt.Color(102, 102, 102));
        inputMinCre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputMinCre.setCaretColor(new java.awt.Color(0, 0, 0));
        inputMinCre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputMinCre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputMinCre.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jlbMaxCreditosPermitidos.setText("Maximo de creditos Permitidos");

        inputMaxCre.setBackground(new java.awt.Color(246, 245, 245));
        inputMaxCre.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputMaxCre.setForeground(new java.awt.Color(102, 102, 102));
        inputMaxCre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputMaxCre.setCaretColor(new java.awt.Color(0, 0, 0));
        inputMaxCre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputMaxCre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputMaxCre.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        btnGuardarConfiguracion.setBackground(new java.awt.Color(0, 102, 0));
        btnGuardarConfiguracion.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        btnGuardarConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarConfiguracion.setText("Guardar");
        btnGuardarConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConfiguracionActionPerformed(evt);
            }
        });

        pnlInfo.setBackground(new java.awt.Color(51, 0, 51));
        pnlInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Numeros de Hormigas:");

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Iteraciones maximas:");

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Minimo de cursos de permitidos:");

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Maximo de cursos permitidos:");

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Minimo de creditos permitidos:");

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Maximo de cursos Permitidos:");

        jlbInfoNumHormigas.setForeground(new java.awt.Color(204, 204, 204));
        jlbInfoNumHormigas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbInfoNumHormigas.setText("10");

        jlbInfoIterMax.setForeground(new java.awt.Color(204, 204, 204));
        jlbInfoIterMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbInfoIterMax.setText("10");

        jlbInfoMinCursosPermitidos.setForeground(new java.awt.Color(204, 204, 204));
        jlbInfoMinCursosPermitidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbInfoMinCursosPermitidos.setText("10");

        jlbInfoMaxCursosPermitidos.setForeground(new java.awt.Color(204, 204, 204));
        jlbInfoMaxCursosPermitidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbInfoMaxCursosPermitidos.setText("10");

        jlbInfoMinCreditosPermitidos.setForeground(new java.awt.Color(204, 204, 204));
        jlbInfoMinCreditosPermitidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbInfoMinCreditosPermitidos.setText("10");

        jlbInfoMaxCreditosPermitidos.setForeground(new java.awt.Color(204, 204, 204));
        jlbInfoMaxCreditosPermitidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbInfoMaxCreditosPermitidos.setText("10");

        jlbInfovalores.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbInfovalores.setForeground(new java.awt.Color(204, 204, 204));
        jlbInfovalores.setText("Valores:");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbInfovalores)
                .addGap(104, 104, 104))
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbInfoIterMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbInfoNumHormigas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbInfoMaxCreditosPermitidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jlbInfoMinCursosPermitidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbInfoMaxCursosPermitidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbInfoMinCreditosPermitidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbInfovalores)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jlbInfoNumHormigas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlbInfoIterMax, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jlbInfoMinCursosPermitidos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jlbInfoMaxCursosPermitidos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jlbInfoMinCreditosPermitidos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlbInfoMaxCreditosPermitidos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jlbAlert.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNumHormigas)
                            .addComponent(inputNumHormigas, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbMinCursosPermitidos)
                            .addComponent(inputMinCur, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbMinCreditosPermitidos)
                            .addComponent(inputMinCre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputMaxCre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbMaxCreditosPermitidos)
                            .addComponent(jLabel3)
                            .addComponent(jlbMaxCursosPermitidos)
                            .addComponent(inputMaxCur, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputIterMax, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnGuardarConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbNumHormigas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputNumHormigas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbMinCursosPermitidos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputMinCur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbMaxCursosPermitidos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputMaxCur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbMinCreditosPermitidos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputMinCre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbMaxCreditosPermitidos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputMaxCre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputIterMax, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(jlbAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnGuardarConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout pOConfigLayout = new javax.swing.GroupLayout(pOConfig);
        pOConfig.setLayout(pOConfigLayout);
        pOConfigLayout.setHorizontalGroup(
            pOConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pOConfigLayout.setVerticalGroup(
            pOConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnOpciones.add(pOConfig, "pOConfig");

        pOCurriculas.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setOpaque(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tbListaPreRequisitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbListaPreRequisitos);
        if (tbListaPreRequisitos.getColumnModel().getColumnCount() > 0) {
            tbListaPreRequisitos.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        inputAPCodigo.setBackground(new java.awt.Color(246, 245, 245));
        inputAPCodigo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputAPCodigo.setForeground(new java.awt.Color(102, 102, 102));
        inputAPCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputAPCodigo.setCaretColor(new java.awt.Color(0, 0, 0));
        inputAPCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputAPCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputAPCodigo.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabel23.setText("Codigo");

        jLabel24.setText("Nombre");

        inputAPNombre.setBackground(new java.awt.Color(246, 245, 245));
        inputAPNombre.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputAPNombre.setForeground(new java.awt.Color(102, 102, 102));
        inputAPNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputAPNombre.setCaretColor(new java.awt.Color(0, 0, 0));
        inputAPNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputAPNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputAPNombre.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabel25.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel25.setText("Agregar Plan de estudio");

        jLabel26.setText("Creditos");

        cbxCreditos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));

        inputAPPreReq.setBackground(new java.awt.Color(246, 245, 245));
        inputAPPreReq.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputAPPreReq.setForeground(new java.awt.Color(102, 102, 102));
        inputAPPreReq.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputAPPreReq.setCaretColor(new java.awt.Color(0, 0, 0));
        inputAPPreReq.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputAPPreReq.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputAPPreReq.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabel27.setText("Pre-Requisito");

        btnAgregarCurso.setBackground(new java.awt.Color(0, 102, 255));
        btnAgregarCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCurso.setText("Agregar Curso");
        btnAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCursoActionPerformed(evt);
            }
        });

        btnAgregarPlan.setBackground(new java.awt.Color(51, 102, 0));
        btnAgregarPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPlan.setText("Agregar Plan");
        btnAgregarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPlanActionPerformed(evt);
            }
        });

        jLabel30.setText("Nombre del Plan");

        inputAPNombrePlan.setBackground(new java.awt.Color(246, 245, 245));
        inputAPNombrePlan.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputAPNombrePlan.setForeground(new java.awt.Color(102, 102, 102));
        inputAPNombrePlan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        inputAPNombrePlan.setCaretColor(new java.awt.Color(0, 0, 0));
        inputAPNombrePlan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputAPNombrePlan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputAPNombrePlan.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setText("Lista de Cursos");

        btnAgregarPreReq.setBackground(new java.awt.Color(0, 0, 51));
        btnAgregarPreReq.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnAgregarPreReq.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPreReq.setText("+");
        btnAgregarPreReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPreReqActionPerformed(evt);
            }
        });

        tbListaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane14.setViewportView(tbListaCursos);
        if (tbListaCursos.getColumnModel().getColumnCount() > 0) {
            tbListaCursos.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbListaCursos.getColumnModel().getColumn(0).setMaxWidth(40);
            tbListaCursos.getColumnModel().getColumn(1).setPreferredWidth(160);
            tbListaCursos.getColumnModel().getColumn(1).setMaxWidth(160);
            tbListaCursos.getColumnModel().getColumn(3).setPreferredWidth(80);
            tbListaCursos.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jlbAlertAPCursoAdd.setForeground(new java.awt.Color(204, 0, 0));

        jlbAlertAPPreReq.setForeground(new java.awt.Color(204, 0, 0));

        jlbAlertAPnombrePlan.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)
                                .addComponent(inputAPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(btnAgregarCurso)
                                    .addGap(47, 47, 47)
                                    .addComponent(jlbAlertAPCursoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel27)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(inputAPPreReq, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(btnAgregarPreReq)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jlbAlertAPPreReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel24)
                                                    .addComponent(inputAPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel26)
                                                    .addComponent(cbxCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(113, 113, 113))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(inputAPNombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jlbAlertAPnombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputAPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputAPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAgregarPreReq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputAPPreReq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbAlertAPPreReq, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbAlertAPCursoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(inputAPNombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlbAlertAPnombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout pOCurriculasLayout = new javax.swing.GroupLayout(pOCurriculas);
        pOCurriculas.setLayout(pOCurriculasLayout);
        pOCurriculasLayout.setHorizontalGroup(
            pOCurriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOCurriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
                .addContainerGap())
        );
        pOCurriculasLayout.setVerticalGroup(
            pOCurriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOCurriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnOpciones.add(pOCurriculas, "pOCurriculas");

        pnlPlanGenerado2.setBackground(new java.awt.Color(231, 228, 228));
        pnlPlanGenerado2.setPreferredSize(new java.awt.Dimension(963, 800));

        jScrollPane3.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setOpaque(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(939, 3200));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(Table1);
        if (Table1.getColumnModel().getColumnCount() > 0) {
            Table1.getColumnModel().getColumn(0).setPreferredWidth(40);
            Table1.getColumnModel().getColumn(0).setMaxWidth(40);
            Table1.getColumnModel().getColumn(1).setPreferredWidth(160);
            Table1.getColumnModel().getColumn(1).setMaxWidth(160);
            Table1.getColumnModel().getColumn(3).setPreferredWidth(80);
            Table1.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel33.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel33.setText("Plan de estudio generado");

        jLabel39.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("CICLO 1");

        jLabel40.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("CICLO 2");

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(Table2);
        if (Table2.getColumnModel().getColumnCount() > 0) {
            Table2.getColumnModel().getColumn(0).setMaxWidth(40);
            Table2.getColumnModel().getColumn(1).setMaxWidth(160);
            Table2.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel41.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("CICLO 3");

        Table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(Table3);
        if (Table3.getColumnModel().getColumnCount() > 0) {
            Table3.getColumnModel().getColumn(0).setMaxWidth(40);
            Table3.getColumnModel().getColumn(1).setMaxWidth(160);
            Table3.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel42.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("CICLO 4");

        Table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(Table4);
        if (Table4.getColumnModel().getColumnCount() > 0) {
            Table4.getColumnModel().getColumn(0).setMaxWidth(40);
            Table4.getColumnModel().getColumn(1).setMaxWidth(160);
            Table4.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel43.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("CICLO 5");

        Table5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(Table5);
        if (Table5.getColumnModel().getColumnCount() > 0) {
            Table5.getColumnModel().getColumn(0).setMaxWidth(40);
            Table5.getColumnModel().getColumn(1).setMaxWidth(160);
            Table5.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel44.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("CICLO 6");

        Table6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(Table6);
        if (Table6.getColumnModel().getColumnCount() > 0) {
            Table6.getColumnModel().getColumn(0).setMaxWidth(40);
            Table6.getColumnModel().getColumn(1).setMaxWidth(160);
            Table6.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel45.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("CICLO 7");

        Table7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(Table7);
        if (Table7.getColumnModel().getColumnCount() > 0) {
            Table7.getColumnModel().getColumn(0).setMaxWidth(40);
            Table7.getColumnModel().getColumn(1).setMaxWidth(160);
            Table7.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel46.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("CICLO 8");

        Table8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(Table8);
        if (Table8.getColumnModel().getColumnCount() > 0) {
            Table8.getColumnModel().getColumn(0).setMaxWidth(40);
            Table8.getColumnModel().getColumn(1).setMaxWidth(160);
            Table8.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel47.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("CICLO 9");

        Table9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane12.setViewportView(Table9);
        if (Table9.getColumnModel().getColumnCount() > 0) {
            Table9.getColumnModel().getColumn(0).setMaxWidth(40);
            Table9.getColumnModel().getColumn(1).setMaxWidth(160);
            Table9.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel48.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("CICLO 10");

        Table10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Creditos", "Prerequisitos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(Table10);
        if (Table10.getColumnModel().getColumnCount() > 0) {
            Table10.getColumnModel().getColumn(0).setMaxWidth(40);
            Table10.getColumnModel().getColumn(1).setMaxWidth(160);
            Table10.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jlbNombrePlanG.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jlbNombrePlanG.setForeground(new java.awt.Color(51, 0, 102));
        jlbNombrePlanG.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNombrePlanG.setText(" ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jLabel39)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                    .addGap(331, 331, 331)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel46)
                                                        .addComponent(jLabel47)
                                                        .addComponent(jLabel48))))
                                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(331, 331, 331)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel43)
                                                .addComponent(jLabel44)
                                                .addComponent(jLabel45))))
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(331, 331, 331)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel40)
                                        .addComponent(jLabel41)
                                        .addComponent(jLabel42))))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbNombrePlanG, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNombrePlanG, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel46)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel48)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jScrollPane3.setViewportView(jPanel6);

        javax.swing.GroupLayout pnlPlanGenerado2Layout = new javax.swing.GroupLayout(pnlPlanGenerado2);
        pnlPlanGenerado2.setLayout(pnlPlanGenerado2Layout);
        pnlPlanGenerado2Layout.setHorizontalGroup(
            pnlPlanGenerado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanGenerado2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        pnlPlanGenerado2Layout.setVerticalGroup(
            pnlPlanGenerado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanGenerado2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnOpciones.add(pnlPlanGenerado2, "pnlPlanGenerado2");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnGenerarPlan.setBackground(new java.awt.Color(0, 0, 102));
        btnGenerarPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarPlan.setText("Generar Plan");
        btnGenerarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPlanActionPerformed(evt);
            }
        });

        cbxListaPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxListaPlanesActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel31.setText("Lista de Planes de estudio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbxListaPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnGenerarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxListaPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPlanGenrado1Layout = new javax.swing.GroupLayout(pnlPlanGenrado1);
        pnlPlanGenrado1.setLayout(pnlPlanGenrado1Layout);
        pnlPlanGenrado1Layout.setHorizontalGroup(
            pnlPlanGenrado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanGenrado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlanGenrado1Layout.setVerticalGroup(
            pnlPlanGenrado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanGenrado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnOpciones.add(pnlPlanGenrado1, "pnlPlanGenerado1");

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addComponent(pNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void init() {
        inicio = new VistaInicio();
        inicio.setVisible(true);
        Timer timer = new Timer(10000, (ActionEvent e) -> {
            setVisible(true);
            inicio.setVisible(false);
        });

        timer.start();

    }
    private void pConfigMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pConfigMouseReleased

        lbConfig.setForeground(Color.white);
        lbCurriculas.setForeground(new Color(204, 204, 204));
        lbResult.setForeground(new Color(204, 204, 204));

        Lay.show(pnOpciones, "pOConfig");
    }//GEN-LAST:event_pConfigMouseReleased

    private void pCurriculasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCurriculasMouseReleased
        lbConfig.setForeground(new Color(204, 204, 204));
        lbCurriculas.setForeground(Color.white);
        lbResult.setForeground(new Color(204, 204, 204));

        Lay.show(pnOpciones, "pOCurriculas");


    }//GEN-LAST:event_pCurriculasMouseReleased

    private void pnlNavPlanGeneradoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNavPlanGeneradoMouseReleased
        lbConfig.setForeground(new Color(204, 204, 204));
        lbCurriculas.setForeground(new Color(204, 204, 204));

        lbResult.setForeground(Color.white);

        Lay.show(pnOpciones, "pnlPlanGenerado1");
    }//GEN-LAST:event_pnlNavPlanGeneradoMouseReleased

    private void btnGenerarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPlanActionPerformed

        Malla.descargarDatos("src\\main\\java\\pe\\edu\\unmsm\\modelo\\datos\\curriculas\\" + cbxListaPlanes.getSelectedItem() + ".txt");

        co = new Coordinador();
        co.comenzarGeneracion();
        Interface.limpiarTablas(Table1, Table2, Table3, Table4, Table5, Table6, Table7, Table8, Table9, Table10);
        Interface.generarTablas(Table1, Table2, Table3, Table4, Table5, Table6, Table7, Table8, Table9, Table10);

        jlbNombrePlanG.setText("" + cbxListaPlanes.getSelectedItem());
        Lay.show(pnOpciones, "pnlPlanGenerado2");


    }//GEN-LAST:event_btnGenerarPlanActionPerformed

    private void btnGuardarConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConfiguracionActionPerformed
        String resultado = Interface.configurarVariables(inputNumHormigas,
                inputIterMax,
                inputMinCur,
                inputMaxCur,
                inputMinCre,
                inputMaxCre);

        if (resultado.equals("Configuracion Guardada")) {
            Interface.establecerInfoVariables(jlbInfoNumHormigas,
                    jlbInfoIterMax,
                    jlbInfoMinCursosPermitidos,
                    jlbInfoMaxCursosPermitidos,
                    jlbInfoMinCreditosPermitidos,
                    jlbInfoMaxCreditosPermitidos);

            jlbAlert.setText(resultado);
            jlbAlert.setForeground(Color.green);
        } else {
            jlbAlert.setText(resultado);
            jlbAlert.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnGuardarConfiguracionActionPerformed

    private void cbxListaPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxListaPlanesActionPerformed


    }//GEN-LAST:event_cbxListaPlanesActionPerformed


    private void btnAgregarPreReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPreReqActionPerformed

        String preRequisito = inputAPPreReq.getText().trim();

        if (preRequisito.isEmpty()) {
            jlbAlertAPPreReq.setText("PreRequisito vacio");
        } else {

            listaPreReq.add(preRequisito);
            Interface.actualizarTablaPreReq(listaPreReq, tbListaPreRequisitos);
            inputAPPreReq.setText("");
        }

    }//GEN-LAST:event_btnAgregarPreReqActionPerformed

    private void btnAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCursoActionPerformed

        String result = Interface.agregarCurso(inputAPCodigo, inputAPNombre, cbxCreditos, listaPreReq, tbListaCursos, plan);
        if (result.equals("Curso Agregado")) {
            jlbAlertAPCursoAdd.setForeground(Color.green);
            inputAPNombre.setText("");
            inputAPCodigo.setText("");
            inputAPPreReq.setText("");
        } else {
            jlbAlertAPCursoAdd.setForeground(Color.red);
        }
        jlbAlertAPCursoAdd.setText(result);
    }//GEN-LAST:event_btnAgregarCursoActionPerformed

    private void btnAgregarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPlanActionPerformed
        String result = Interface.agregarPlan(plan, inputAPNombrePlan);
        if (result.equals("Nombre del plan vacio")) {
            jlbAlertAPnombrePlan.setForeground(Color.red);
        } else {
            jlbAlertAPnombrePlan.setForeground(Color.green);
            inputAPNombrePlan.setText("");
        }
        jlbAlertAPnombrePlan.setText(result);
    }//GEN-LAST:event_btnAgregarPlanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table10;
    private javax.swing.JTable Table2;
    private javax.swing.JTable Table3;
    private javax.swing.JTable Table4;
    private javax.swing.JTable Table5;
    private javax.swing.JTable Table6;
    private javax.swing.JTable Table7;
    private javax.swing.JTable Table8;
    private javax.swing.JTable Table9;
    private javax.swing.JButton btnAgregarCurso;
    private javax.swing.JButton btnAgregarPlan;
    private javax.swing.JButton btnAgregarPreReq;
    private javax.swing.JButton btnGenerarPlan;
    private javax.swing.JButton btnGuardarConfiguracion;
    private javax.swing.JComboBox<String> cbxCreditos;
    private javax.swing.JComboBox<String> cbxListaPlanes;
    private javax.swing.JTextField inputAPCodigo;
    private javax.swing.JTextField inputAPNombre;
    private javax.swing.JTextField inputAPNombrePlan;
    private javax.swing.JTextField inputAPPreReq;
    private javax.swing.JTextField inputIterMax;
    private javax.swing.JTextField inputMaxCre;
    private javax.swing.JTextField inputMaxCur;
    private javax.swing.JTextField inputMinCre;
    private javax.swing.JTextField inputMinCur;
    private javax.swing.JTextField inputNumHormigas;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlbAlert;
    private javax.swing.JLabel jlbAlertAPCursoAdd;
    private javax.swing.JLabel jlbAlertAPPreReq;
    private javax.swing.JLabel jlbAlertAPnombrePlan;
    private javax.swing.JLabel jlbInfoIterMax;
    private javax.swing.JLabel jlbInfoMaxCreditosPermitidos;
    private javax.swing.JLabel jlbInfoMaxCursosPermitidos;
    private javax.swing.JLabel jlbInfoMinCreditosPermitidos;
    private javax.swing.JLabel jlbInfoMinCursosPermitidos;
    private javax.swing.JLabel jlbInfoNumHormigas;
    private javax.swing.JLabel jlbInfovalores;
    private javax.swing.JLabel jlbMaxCreditosPermitidos;
    private javax.swing.JLabel jlbMaxCursosPermitidos;
    private javax.swing.JLabel jlbMinCreditosPermitidos;
    private javax.swing.JLabel jlbMinCursosPermitidos;
    private javax.swing.JLabel jlbNombrePlanG;
    private javax.swing.JLabel jlbNumHormigas;
    private javax.swing.JLabel lbConfig;
    private javax.swing.JLabel lbCurriculas;
    private javax.swing.JLabel lbResult;
    private javax.swing.JPanel pConfig;
    private javax.swing.JPanel pCurriculas;
    private javax.swing.JPanel pNav;
    private javax.swing.JPanel pOConfig;
    private javax.swing.JPanel pOCurriculas;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel pnOpciones;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlNavPlanGenerado;
    private javax.swing.JPanel pnlPlanGenerado2;
    private javax.swing.JPanel pnlPlanGenrado1;
    private javax.swing.JTable tbListaCursos;
    private javax.swing.JTable tbListaPreRequisitos;
    // End of variables declaration//GEN-END:variables
}
